### ISSUE TITLE
PaddingSymmetrical should accept horizontal and vertical paddings

### ISSUE THREAD

**Issue by aryzhov** [arklabsnz/Padder#1]
In the current release 1.1.0, PaddingSymmetrical accepts only a single padding value, effectively making it equivalent to PaddingAll.

P.S.: Please put a link to this repo in `pubspec.yaml` as `homepage`.

**Comment by josh-burton** [comment]
Thanks for this and sorry for the delay.

I've just published 1.2.0 with these changes.
